:sparkles: online runner use essential build

diff --git a/.github/workflows/otto-build.yml b/.github/workflows/otto-build.yml
--- a/.github/workflows/otto-build.yml
+++ b/.github/workflows/otto-build.yml
@@ -8,7 +8,7 @@ on:
     branches:
       - main
     paths:
-      - .config
+      - configs/essential.config
       - .github/workflows/otto-build.yml
 
   workflow_dispatch:
@@ -118,7 +118,7 @@ jobs:
         run: |
           export FORCE_UNSAFE_CONFIGURE=1
           cd ${{ github.workspace }}/${{ env.WORKDIR }}
-          cp ${{ github.workspace }}/.config .
+          cp ${{ github.workspace }}/configs/essential.config .config
 
           # 修改默认 IP 为 192.168.114.1/24
           # 避免与光猫冲突
@@ -134,15 +134,34 @@ jobs:
           cd ${{ github.workspace }}/${{ env.WORKDIR }}
           make download -j$(nproc)
 
+      - name: Patch Ripgrep
+        run: |
+          cd ${{ github.workspace }}/${{ env.WORKDIR }}
+          MF="feeds/packages/utils/ripgrep/Makefile"
+          if [ -f "$MF" ]; then
+            grep -qF "PKG_BUILD_FLAGS:=no-lto" "$MF" || \
+              sed -i '/^include $(INCLUDE_DIR)\/package\.mk$/i PKG_BUILD_FLAGS:=no-lto' "$MF"
+            grep -nF "PKG_BUILD_FLAGS:=no-lto" "$MF"
+          else
+            echo "Makefile not found: $MF" >&2
+            exit 1
+          fi
+
       - name: Patch Netdata
         run: |
           cd ${{ github.workspace }}/${{ env.WORKDIR }}
-          MF="feeds/packages/admin/netdata/Makefile"; \
-          if [ -f "$MF" ]; then \
-            grep -qF -- "--disable-cloud" "$MF" || printf '\nCONFIGURE_ARGS += --disable-cloud\n' >> "$MF"; \
-            grep -n -- "--disable-cloud" "$MF"; \
-          else \
-            echo "Makefile not found: $MF" >&2; exit 1; \
+          MF="feeds/packages/admin/netdata/Makefile"
+          if [ -f "$MF" ]; then
+            grep -qFx '$(eval $(call BuildPackage,netdata))' "$MF" || {
+              echo "BuildPackage definition not found: $MF" >&2
+              exit 1
+            }
+            sed -i '/^CONFIGURE_ARGS += --disable-cloud$/d' "$MF"
+            sed -i '/^\$(eval \$(call BuildPackage,netdata))$/i CONFIGURE_ARGS += --disable-cloud' "$MF"
+            grep -n -B1 -A1 -F "CONFIGURE_ARGS += --disable-cloud" "$MF"
+          else
+            echo "Makefile not found: $MF" >&2
+            exit 1
           fi
 
       - name: Build
